# Generated by Django 4.0.2 on 2022-04-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('event_type', models.IntegerField(choices=[(0, 'Meeting'), (1, 'Schedule Appointment'), (2, 'Repair'), (3, 'Maintainance'), (4, 'Verification'), (5, 'Viewing'), (6, 'Check Up'), (7, 'Document Upload')])),
                ('description', models.CharField(max_length=240)),
                ('status', models.IntegerField(choices=[(0, 'Unscheduled'), (1, 'Scheduled'), (2, 'Completed'), (3, 'Upcoming')])),
                ('dependent_on', models.CharField(max_length=32)),
            ],
        ),
    ]
